name: ğŸ¤– Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: ["main"]

jobs:
  quality:
    name: â¬£ Linting
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: â” Setup pnpm and Node, install dependencies
        uses: ./.github/composites/setup-pnpm
        with:
          node-version: 22
          cache: "pnpm"

      - name: ğŸ”¬ Run linters
        run: pnpm run lint

  typecheck:
    name: Ê¦ TypeScript
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: â” Setup pnpm and Node, install dependencies
        uses: ./.github/composites/setup-pnpm
        with:
          node-version: 22
          cache: "pnpm"

      - name: ğŸ” Run Typecheck
        run: pnpm run typecheck

  unused-dependencies:
    name: ğŸ” Knip
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: â” Setup pnpm and Node, install dependencies
        uses: ./.github/composites/setup-pnpm
        with:
          node-version: 22
          cache: "pnpm"

      - name: ğŸ” Run knip
        run: pnpm run knip
